#!/bin/bash

echo "-------------------------------------------------------------------"
echo "!!! Running deploy shell script                                 !!!"
echo ""

echo ""
echo "!!! Deploy script complete ...                                  !!!"
echo "-------------------------------------------------------------------"